name: MLOps Pipeline

on:
  workflow_dispatch:
  push:
    branches:    
      - dev

env:
  PYTHON_VERSION: 3.6
  RESOURCE_GROUP: mlops-demo
  REGION: westeurope
  AZUREML_WORKSPACE_NAME: mlops-mlwrksp

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install Python Requirements
      run: ./install_requirements.sh
      working-directory: setup
    - name: Data Quality Check
      run: pytest tests/unit/data_test.py --doctest-modules --junitxml=junit/test-results.xml --cov=data_test --cov-report=xml --cov-report=html
    - name: Publish Data Quality Check
      uses: EnricoMi/publish-unit-test-result-action@v1.6
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: junit/**/*.xml
        check_name: Data Quality Check
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Add Azure ML CLI Extension
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az extension add -n azure-cli-ml
    - name: Create Azure ML Service Workspace
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az ml workspace create -g "$RESOURCE_GROUP" -w "$AZUREML_WORKSPACE_NAME" -l "$REGION" --exist-ok --yes
